name: Build

on:
  push:
    branches: [ actions ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v5
    - uses: lukka/get-cmake@latest
    - uses: lukka/run-vcpkg@v11

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
       brew update
       brew install apr subversion

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libapr1-dev libsvn-dev

    - name: Configure
      run: cmake --preset=ninja

    - name: Build
      run: cmake --build build --config=Release

    - name: Test
      run: cmake --build build && ctest --test-dir build

      # TODO:
      # Fix internal linkage on Linux